version: "2"

networks:
  example:
    external: false

services:
  server:
    # Set the docker hub username and repository name here
    image: chmac/generouslabs-share-server:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - NODE_ENV=production
      # Add any custom environment variables here
    restart: always
    networks:
      - example
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data:/user/src/data
      - ./templates:/user/src/templates
    ports:
      # This exposes port 4000 inside the container to 4800 on the host
      - "4800:8000"
